spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 4.0.21
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb+srv://admin:password1516@cluster0.lqjujzh.mongodb.net/?retryWrites=true&w=majority
      port: 27017
      database: webflux_poc
---
spring:
  config:
    activate:
      on-profile: nonprod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
logging:
  level:
    root: info